fix: potential fix for repo in gke
Signed-off-by: Kush Bhalodi <kush.bhalodi@ibm.com>

diff --git a/gke-manifest/opensearch-benchmark-worker-template.yaml b/gke-manifest/opensearch-benchmark-worker-template.yaml
--- a/gke-manifest/opensearch-benchmark-worker-template.yaml
+++ b/gke-manifest/opensearch-benchmark-worker-template.yaml
@@ -116,7 +116,8 @@ spec:
             else
               echo "Workspace already exists, pulling latest changes..."
               cd /workspace
-              git fetch origin acl-benchmarking
+              git remote set-url origin https://github.com/kush992/opensearch-benchmark-automation.git
+              git fetch origin acl-benchmarking || echo "Git fetch failed, using existing version"
               git checkout acl-benchmarking || echo "Git checkout failed, using existing version"
               git pull origin acl-benchmarking || echo "Git pull failed, using existing version"
             fi
